openai:
  key:
  url:
  model: gpt-4o
deepseekKey:
cookie:
  twitter: auth_token=
  pixiv:
  bilbili:
  weibo: SUB=; SUBP=
prompts:
  key: value
rss:
  interval: 60 # minutes
  folder: D:/Videos
  maxDuration: 1200 # seconds, 20 minutes
  urls:
    - https://example.com/rss.xml
twitterKey: # docs: https://github.com/Rishikant181/Rettiwt-API
