openai:
  key:
  url:
  model: gpt-4o
deepseek:
  key:
  url: https://ark.cn-beijing.volces.com/api/v3
  model:
gemini:
  key:
  model:
cookie:
  twitter: auth_token=
  pixiv:
  bilbili:
  weibo: SUB=; SUBP=
prompts:
  key: value
twitterKey: # docs: https://github.com/Rishikant181/Rettiwt-API
