openai:
  key:
  url:
cookie:
  twitter: auth_token=
  pixiv:
  bilbili:
prompts:
  key: value
rss:
  interval: 60 # minutes
  folder: D:/Videos
  maxDuration: 1200 # seconds, 20 minutes
  urls:
    - https://example.com/rss.xml
