import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { dir } from '~/utils/nodejs'

const listOutput = execSync('scoop list').toString()

const packages = listOutput
  .split('\n')
  .slice(6)
  .map((line) => {
    const parts = line.trim().split(/\s+/)
    const name = parts[0]
    const version = parts[1]

    if (!name || !version)
      return ''

    let source = parts[2] || ''
    if (source === '<auto-generated>')
      source = ''
    return `${source ? `${source}/` : ''}${name}`
  })
  .filter(Boolean)
  .sort()

console.log(`Found ${packages.length} packages`)

console.log(packages)

const file = dir('D:/Scoop/scoop-list.txt')
writeFileSync(file, packages.join('\n'), { encoding: 'utf-8' })
