name: Checkin
on:
  workflow_dispatch:
  schedule:
    # Every day at 00:01 UTC+8
    - cron: '1 16 * * *'

jobs:
  checkin:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install typescript runtime
        run: pnpm add -g tsx

      - name: Run checkin
        run: tsx cli/checkin.ts
        env:
          WEIBO_COOKIE: ${{ secrets.WEIBO_COOKIE }}
