name: Daily-Run

on:
  schedule:
    - cron: '16 16 * * *' # UTC 时间 16:00，对应北京时间 00:00
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run scripts
        env:
          WEIBO_COOKIE: ${{ secrets.WEIBO_COOKIE }}
        run: bun run cli/daily-run.ts
